name: Adhoc
on:
  push:
    tags:
      - 'v*.*.*-*'
jobs:
  adhoc:
    runs-on: windows-latest
    strategy:
      matrix:
        keys: [
          'https://smartstore.naver.com/beenhoney',
          'https://smartstore.naver.com/bsoh1118?NaPm=ct%3Dlf4qdc9d%7Cci%3Dshopn%7Ctr%3Dslsl%7Chk%3Db84fc710b7a50b13532ca539c74b88e3c01e428e%7Ctrx%3Dundefined',
        ]
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'lubiksss/KPT26-smart-info'
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - run: npm run start ${{matrix.keys}}
      - if: ${{ always() }}
        uses: actions/upload-artifact@v3
        with:
          name: result
          path: './test/*.xlsx'
          retention-days: 1

  collect:
    runs-on: ubuntu-latest
    needs: adhoc
    steps:
      - uses: actions/checkout@v3
        with:
          repository: 'lubiksss/KPT0-collecting-xlsx'
          token: ${{ secrets.GH_TOKEN }}
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - run: npm ci
      - uses: actions/download-artifact@v3
        with:
          name: result
          path: './test'
      - run: node index.js test
      - uses: actions/upload-artifact@v3
        with:
          name: result
          path: './*.xlsx'
          retention-days: 1

  adhoc-noti-success:
    needs: adhoc
    if: ${{ always() && contains(needs.adhoc.result, 'success') }}
    runs-on: ubuntu-latest
    steps:
      - name: Adhoc Success
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Author: ${{github.actor}}
            Status: 😚 **Success**
            Action: https://github.com/${{ github.repository }}/actions
            **Adhoc**

  adhoc-noti-fail:
    needs: adhoc
    if: ${{ always() && contains(needs.adhoc.result, 'fail') }}
    runs-on: ubuntu-latest
    steps:
      - name: Adhoc Failure
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_TO }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          message: |
            Author: ${{github.actor}}
            Status: 😱 **Failure**
            Action: https://github.com/${{ github.repository }}/actions
            **Adhoc**
